def find_core_plugin(start_path)
  current_path = File.expand_path(start_path)
  until current_path == "/"
    folder_path = File.join(current_path, 'scandit-react-native-datacapture-core')
    if Dir.exist?(folder_path)
      return folder_path
    end
    current_path = File.dirname(current_path)
  end
  nil
end

scandit_core_path = find_core_plugin(__dir__)

require_relative File.join(scandit_core_path, 'scripts/detect_frameworks')

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip


platform :ios, '15.1'
prepare_react_native_project!
inhibit_all_warnings!
target 'USDLVerificationSample' do
  config = use_native_modules!



  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )


  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
        config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
        config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
      end
    end
  end
end
